export const USUARIO = {
  DADOS_USER: "DADOS_USER",
  TOP_SUGESTOES: "TOP_SUGESTOES",
  SUGESTOES_FAVORITAS: "SUGESTOES_FAVORITAS",
};

export const LOADING = {
  EXIBIR_LOADING: "EXIBIR_LOADING",
  FECHAR_LOADING: "FECHAR_LOADING",
};


export const MODAL = {
  EXIBIR: "EXIBIR",
  FECHAR: "FECHAR",
  TITULO: "TITULO",
  DESCRICAO: "DESCRICAO",
  FUNCAO_PADRAO: "FUNCAO_PADRAO",
};

export const TICKET = {
  TIPO_TICKET: "TIPO_TICKET",
};

export const SUGESTAO = {
  GRAFICO_PENDENTE: "GRAFICO_PENDENTE",
  GRAFICO_CATEGORIA: "GRAFICO_CATEGORIA",
  GRAFICO_AGUARDANDO: "GRAFICO_AGUARDANDO",
  GRAFICO_TOP_FAVORITOS: "GRAFICO_TOP_FAVORITOS",
  NOVAS_SUGESTAO: "NOVAS_SUGESTAO",
  PENDENTES: "PENDENTES",
};

export default {
  USUARIO,
  LOADING,
  TICKET,
  SUGESTAO,
  MODAL,
};
