export const USUARIO = {
  DADOS_USER: "DADOS_USER",
  TOP_SUGESTOES: "TOP_SUGESTOES",
  SUGESTOES_FAVORITAS: "SUGESTOES_FAVORITAS",
};

export const LOADING = {
  EXIBIR_LOADING: "EXIBIR_LOADING",
  FECHAR_LOADING: "FECHAR_LOADING",
};


export const MODAL = {
  EXIBIR: "EXIBIR",
  FECHAR: "FECHAR",
  TITULO: "TITULO",
  DESCRICAO: "DESCRICAO",
  FUNCAO_PADRAO: "FUNCAO_PADRAO",
};

export const STATUS = {
  TODOS_STATUS: "TODOS_STATUS",
};

export const CATEGORIA = {
  TODAS_CATEGORIA: "TODAS_CATEGORIA",
};

export const SUGESTAO = {
  GRAFICO_PENDENTE: "GRAFICO_PENDENTE",
  GRAFICO_CATEGORIA: "GRAFICO_CATEGORIA",
  GRAFICO_STATUS: "GRAFICO_AGUARDANDO",
  GRAFICO_BARRAS: "GRAFICO_BARRAS",
  TODAS_SUGESTOES: "TODAS_SUGESTOES",
};

export default {
  USUARIO,
  LOADING,
  STATUS,
  SUGESTAO,
  MODAL,
};
