export const USUARIO = {
    DADOS_USER: "DADOS_USER",
    TOP_TICKET: "TOP_TICKET",
    TICKETS_FAVORITOS: "TICKETS_FAVORITOS",
};

export const LOADING = {
    EXIBIR_LOADING: "EXIBIR_LOADING",
    FECHAR_LOADING: "FECHAR_LOADING",
};

export const TICKET = {
    TIPO_TICKET: "TIPO_TICKET",
    TICKET_GRAFICO_PENDENTE: "TICKET_GRAFICO_PENDENTE",
    TICKET_GRAFICO_CATEGORIA: "TICKET_GRAFICO_CATEGORIA",
    TICKET_GRAFICO_SOLUCIONADO: "TICKET_GRAFICO_SOLUCIONADO",
    TICKET_GRAFICO_TOP_FAVORITOS: "TICKET_GRAFICO_TOP_FAVORITOS",
    NOVOS_TICKETS: "NOVOS_TICKETS",
};

export default {
    USUARIO,
    LOADING,
    TICKET,
}